version: '3.8'

services:
  react-app:
    image: node:14
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    command: sh -c "npm install && npm start"